version: '3'

services:
  test_server:
    build: ./server
    environment:
      CI: "${CI}"
    command: npm run test
    volumes:
      - ./server/src:/usr/src/app/src/
  #  links:
  #    - test_database
  #  environment:
  #    - PGHOST=database
  #    - PGDATABASE=postgres
  #    - PGUSER=postgres
    
      
  test_frontend:
    build: ./frontend
    environment:
      CI: "${CI}"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    command: npm run test
