version: '3'

services:
  ################################
  #   Setup postgres container
  ################################
  database:
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data

################################
#   Setup node container
################################
  server:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./server/src:/usr/src/app/src/
    command: npm run dev
      
  frontend:
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    command: npm run start
    build: ./frontend
    ports:
      - 4000:3000
    links:
      - server  
