version: '3'

services:
  ################################
  #   Setup postgres container
  ################################
  database:
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data

################################
#   Setup node container
################################
  server:
    build: ./server
    links:
      - database
    environment:
      - PGHOST=database
      - PGDATABASE=postgres
      - PGUSER=postgres
    command: npm run start

  frontend:
    build: ./frontend
    ports:
      - 80:80
    links:
      - server
    environment:
      - API_URL=http://server:5000
