version: '3'

services:
  test_server:
    build: ./server
    environment:
      CI: "${CI}"
    command: npm run test
  #  links:
  #    - test_database
  #  environment:
  #    - PGHOST=database
  #    - PGDATABASE=postgres
  #    - PGUSER=postgres
    
      
  test_frontend:
    build: ./frontend
    environment:
      CI: "${CI}"
    command: npm run test
