version: '3'

volumes:
  database_data:
    driver: local

services:
################################
#   Setup postgres container
################################
  database:
    image: postgres:latest
    volumes:
      - database_data:/var/lib/postgresql/data

################################
#   Setup node container
################################
  server:
    build: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - database
    environment:
      - PGHOST=database
      - PGDATABASE=postgres
      - PGUSER=postgres
