version: 2

jobs:
  build:
    docker:
      - image: zenika/compose:latest
    working_directory: ~/app

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Start docker-compose
          command: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build
