version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/frontend
    
    steps:
      - checkout

      - run:
          name: NPM install
          command: npm install

      - run:
          name: Run unit tests
          command: npm run test
